GET http://localhost:8080/customers
Accept: application/json

###


GET http://localhost:8080/customers/2
Accept: application/json

###

POST http://localhost:8080/customers
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{ "id":"2","firstName":"Sven","lastName":"Hagen","birthday":"1996-03-09"}

###

DELETE http://localhost:8080/customers/1
Accept: application/json

###